name: Test on push

on: [push]

jobs:
  run-test:
    strategy:
      matrix:
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        java: ['8', '11']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          lein: 'latest'
      - name: Run tests
        run: lein cloverage -n 'phrag.*'
